### ISSUE TITLE
Are the input files available?

### ISSUE THREAD

**Issue by riversdark** [paulrobustelli/CHEM101.6#1]
Hi, I'm trying to run the notebook from lesson 1, but couldn't find the input files, i.e. `butane.pdb` and `butane.gaff2.xml`. As an alternative I've download a butane PDB file from the internet, and used `butane.gaff2.cor1.xml` instead, but I'm running into errors about wrong structures. 

The links to these files are hard links to a local desktop, are they also available somewhere else? Thanks!

**Comment by paulrobustelli** [comment]
Hello,

Here are the lesson materials
________________________________
From: Olivier Ma ***@***.***>
Sent: Wednesday, August 2, 2023 8:05 AM
To: paulrobustelli/CHEM101.6 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paulrobustelli/CHEM101.6] Are the input files available? (Issue #1)


Hi, I'm trying to run the notebook from lesson 1, but couldn't find the input files, i.e. butane.pdb and butane.gaff2.xml. As an alternative I've download a butane PDB file from the internet, and used butane.gaff2.cor1.xml instead, but I'm running into errors about wrong structures.

The links to these files are hard links to a local desktop, are they also available somewhere else? Thanks!

**Comment by riversdark** [comment]
Thanks! And thanks for sharing your lectures :)
